### ISSUE TITLE
Switch between `actual` and `LocalStack` services in the same environment

### ISSUE THREAD

**Issue by bandreit** [localstack-dotnet/localstack-dotnet-client#39]
Hi! I'd like to figure out if there is a way to use a combination of both the actual AWS services and LocalStack in the same environment by still using LocalStack.NET. 

For example: use the LocalStack SQS version (set up through docker) and the actual AWS Cognito service (by picking up a profile that has valid credentials).

Given that the library is [set up](https://github.com/localstack-dotnet/localstack-dotnet-client/blob/72962b732a0c2a542bfa9db1294cc09503225acf/src/LocalStack.Client.Extensions/ServiceCollectionExtensions.cs#L215) to use different authentication models if `UseLocalStack` is set to true, I cannot find a way to figure out service configuration independently.

**Comment by Blind-Striker** [comment]
Hey @bandreit, I haven't tried this specific case myself, but if you register AWS Cognito using the [AddAWSService](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html) method from `AWSSDK.Extensions.NETCore.Setup`, rather than using `AddAwsService` or `AddAWSServiceLocalStack` from LocalStack.NET, you should be able to connect directly to AWS Cognito without involving LocalStack.

**Comment by bandreit** [comment]
@Blind-Striker you are right. Using the different methods for configuring the services works fine. For some reason I remember trying exactly this and failing, but doing it with a clean slate now seems to do the job. Thank you.
